### PR TITLE
Make bb compatible + test runner

### LINKED ISSUE #9: Add babashka support
Hi, thanks for this library.

Wondering if you're interested in adding Babashka support?

I believe (and have tested a bit) that this can be achieved with a single change adding a reader conditional Sci's var type, replacing these lines:
https://github.com/exoscale/interceptor/blob/fe9832be8d7d2d9bc5c0cc743f7495d7750d4920/src/exoscale/interceptor/impl.cljc#L24-L26
With this
```clojure
#?(:bb sci.lang.Var
   :clj clojure.lang.Var
   :cljs clojure.lang.Var)
  (interceptor [v]
    (p/interceptor (deref v)))
```
(Babashka's reader conditionals are explained here: https://book.babashka.org/#_reader_conditionals)

I could provide a PR if you prefer.

Edit: I have noticed this fix only works with a relatively recent version of babashka. It works with v0.9.160 but not with v0.8.2. I could investigate this further and possibly find a more generally compatible solution if you're interested in adding the support

### PR DESCRIPTION
**Pull request by borkdude**
Run `bb test:bb` to run tests with babashka.
Run `bb test:clj` to run tests with JVM Clojure via lein.

Manifold tests were moved to separate namespace since bb can't run manifold.

These changes only work with the newest babashka on master which you can download via:

https://github.com/babashka/babashka-dev-builds

Added CI test runner.

Fixes #9.

### CODE REVIEW

**Comment by borkdude** [comment]
@mpenet Please squash/merge the commits via the Github button, or if you want me to do this prior to merge, let me know.

Do you want to run these tests in CI? I could add a Github Actions runner.

**Comment by mpenet** [comment]
That's looking great thanks. About CI, sure, that'd be a good addition.

**Comment by mpenet** [comment]
About squashing, I usually just "squash & merge" on gh, so don't bother.

**Comment by borkdude** [comment]
@mpenet CI runner added which currently downloads the bb master version. Once I release the next version, we can switch to a stable version in CI.

**Comment by mpenet** [comment]
Looking good! I'll merge in this state and modify things a bit to be backward compatible with the previous behavior wrt to records and release a new version after that. 

Thanks a lot for all your work on this.

**Pull request merged**
